name: test-hermes-v1
description: Tests a library on a nightly
inputs:
  platform:
    description: whether we want to build for iOS or Android
    required: true
  flavor:
    required: true
    description: the flavor we want to run - either debug or release
  retry-count:
    description: Number of retry attempts for failed builds
    required: false
    default: '3'
runs:
  using: composite
  steps:
    - name: Prepare capitalized flavor
      id: prepare-flavor
      shell: bash
      run: |
        CAPITALIZED_FLAVOR=$(echo "${{ inputs.flavor }}" | awk '{print toupper(substr($0, 1, 1)) substr($0, 2)}')
        echo "capitalized_flavor=$CAPITALIZED_FLAVOR" >> $GITHUB_OUTPUT

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Install Maestro
      shell: bash
      run: export MAESTRO_VERSION=1.40.0; curl -Ls "https://get.maestro.mobile.dev" | bash

    - name: Install Maestro dependencies
      if: ${{ inputs.platform == 'ios' }}
      shell: bash
      run: |
        brew tap facebook/fb
        brew install facebook/fb/idb-companion

    - name: Create new app
      shell: bash
      run: |
        cd /tmp
        npx @react-native-community/cli init RNApp --skip-install --version nightly
    
    - name: Apply patch if specified
      shell: bash
      run: |
        if [ -f "$GITHUB_WORKSPACE/patches/hermes-v1.patch" ]; then
          echo "Applying patch: hermes-v1.patch"
          cd /tmp/RNApp
          node "$GITHUB_WORKSPACE/scripts/apply-patch.js" "$GITHUB_WORKSPACE/patches/hermes-v1.patch"
          echo "✅ Patch applied successfully"
        else
          echo "⚠️  Warning: Patch file not found: patches/hermes-v1.patch"
          exit 1
        fi
    
    - name: Install app dependencies with retry
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: ${{ inputs.retry-count }}
        retry_wait_seconds: 15
        shell: bash
        command: |
          cd /tmp/RNApp
          yarn install
        on_retry_command: |
          echo "Cleaning up for yarn retry..."
          cd /tmp/RNApp
          rm -rf node_modules yarn.lock || true
          yarn cache clean || true

    # iOS
    - name: Setup xcode
      if: ${{ inputs.platform == 'ios' }}
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 16.4.0
    - name: Build iOS with retry
      if: ${{ inputs.platform == 'ios' }}
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 45
        max_attempts: ${{ inputs.retry-count }}
        retry_wait_seconds: 30
        shell: bash
        command: |
          cd /tmp/RNApp/ios
          bundle install
          RCT_HERMES_V1_ENABLED=1 bundle exec pod install
          xcodebuild build \
            -workspace "RNApp.xcworkspace" \
            -scheme "RNApp" \
            -configuration "${{ steps.prepare-flavor.outputs.capitalized_flavor }}" \
            -sdk "iphonesimulator" \
            -destination "generic/platform=iOS Simulator" \
            -derivedDataPath "/tmp/RNApp" \
            -quiet
        on_retry_command: |
          echo "Cleaning up for iOS retry..."
          cd /tmp/RNApp/ios
          rm -rf Pods Podfile.lock build
          rm -rf ~/Library/Developer/Xcode/DerivedData/* || true

    # Android
    - name: Build Android with retry
      if: ${{ inputs.platform == 'android' }}
      uses: nick-fields/retry@v3
      env:
        CMAKE_VERSION: 3.31.5
        ORG_GRADLE_PROJECT_reactNativeArchitectures: x86_64
      with:
        timeout_minutes: 45
        max_attempts: ${{ inputs.retry-count }}
        retry_wait_seconds: 30
        shell: bash
        command: |
          cd /tmp/RNApp/android
          ./gradlew assemble${{ steps.prepare-flavor.outputs.capitalized_flavor }}
        on_retry_command: |
          echo "Cleaning up for Android retry..."
          cd /tmp/RNApp/android
          ./gradlew clean || true
          rm -rf build app/build .gradle || true

    - name: Enable KVM group perms
      if: ${{ inputs.platform == 'android' }}
      shell: bash
      run: |
        # ubuntu machines have hardware acceleration available and when we try to create an emulator, the script pauses asking for user input
        # These lines set the rules to reply automatically to that question and unblock the creation of the emulator.
        # source: https://github.com/ReactiveCircus/android-emulator-runner?tab=readme-ov-file#running-hardware-accelerated-emulators-on-linux-runners
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Start Metro in debug
      if: ${{ inputs.flavor == 'debug' }}
      shell: bash
      run: |
        cd /tmp/RNApp
        yarn start &
        echo $! > /tmp/metro.pid
        sleep 5

    - name: Run iOS E2E Tests
      if: ${{ inputs.platform == 'ios' }}
      id: run-tests-ios
      shell: bash
      run: |
        node .github/workflow-scripts/maestro-ios.js \
          "/tmp/RNApp/Build/Products/${{ steps.prepare-flavor.outputs.capitalized_flavor }}-iphonesimulator/RNApp.app" \
          "org.reactjs.native.example.RNApp" \
          "./.github/workflow-scripts/e2e/.maestro/" \
          "Hermes" \
          "${{ steps.prepare-flavor.outputs.capitalized_flavor }}" \
          "/tmp/RNApp"

    - name: Store iOS tests result
      if: ${{ inputs.platform == 'ios' && (success() || failure()) }}
      uses: actions/upload-artifact@v4.3.4
      with:
        name: e2e_ios_hermes_v1_report_${{ inputs.flavor }}
        path: |
          video_record_1.mov
          video_record_2.mov
          video_record_3.mov
          video_record_4.mov
          video_record_5.mov
          report.xml

    - name: Run Android E2E tests
      if: ${{ inputs.platform == 'android' }}
      id: run-tests-android
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 24
        arch: x86_64
        ram-size: '8192M'
        heap-size: '4096M'
        disk-size: '6G'
        cores: '4'
        disable-animations: false
        avd-name: e2e_emulator
        script: |
          node .github/workflow-scripts/maestro-android.js /tmp/RNApp/android/app/build/outputs/apk/${{ inputs.flavor }}/app-${{ inputs.flavor }}.apk com.rnapp ./.github/workflow-scripts/e2e/.maestro/ ${{ inputs.flavor }} /tmp/RNApp

    - name: Store Android tests result
      uses: actions/upload-artifact@v4.3.4
      if: ${{ inputs.platform == 'android' && (success() || failure()) }}
      with:
        name: e2e_android_hermes_v1_report_${{ inputs.flavor }}
        path: |
          report.xml
          screen.mp4

    - name: Stop Metro in debug
      if: ${{ inputs.flavor == 'debug' && always() }}
      shell: bash
      run: |
        METRO_PID=$(cat /tmp/metro.pid)
        kill $METRO_PID || true
        echo "Metro process $METRO_PID stopped."
